### ISSUE TITLE
WalletHelper use $user->getWallet() function not defined

### ISSUE THREAD

**Issue by faboo03** [AppVentus/MangopayBundle#2]
The function $user->getWallet() used in the WalletHelper, should be defined throw an interface to apply to the user.

How do you manage to give a wallet from the userEntity? Injecting the wallet, injecting just a reference ?

**Comment by paulandrieux** [comment]
The walletHelper dos not call getWallet() anymore, but getMangoWalletId() which is defined in the UserInterface.
