### ISSUE TITLE
The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 28 (near "- @appventus_mangopay.mango_api").

### ISSUE THREAD

**Issue by allan-simon** [AppVentus/MangopayBundle#21]
Here's the error message I get when I try to do nothing more than a new of the bundle in the AppKernel 

I'm using PHP7.0 and Symfony3.1 
I've upgraded today to 2.0.1 of this bundle, but it was not working before either.

**Comment by lenybernard** [comment]
Yes, actually, it is related to 2.8 dépréciations:
http://symfony.com/blog/new-in-symfony-2-8-yaml-deprecations
We didn't tried yet with symfony3 but I think just doing what is explained in this link should work.
If you do the change, feel free to fork an submit à pull request.
Thanks you

**Comment by allan-simon** [comment]
ok thanks, I'm going to try to fix and will submit you a PR

**Comment by allan-simon** [comment]
Hello indeed it fixes the issue, I've submitted a PR

**Comment by paulandrieux** [comment]
I merged your PR #22, thanks again !

**Comment by allan-simon** [comment]
thanks actually for pointing out the documentation, what would be awesome is if you could make a minor release of the bundle on packagist so the bundle can be usable on symfony3 :)

**Comment by paulandrieux** [comment]
Yep I just made the 2.0.2 release
