### ISSUE TITLE
Could we have some documentation ?

### ISSUE THREAD

**Issue by aslafy-z** [AppVentus/MangopayBundle#8]
I'm trying to use you bundle to make a direct payment (using PaymentDirectHelper), and i'm trying to know what do i need to pass to create method.
Could you give me a basic example of how to use it please ?
Thanks a lot !

**Comment by lenybernard** [comment]
:+1:

**Comment by aslafy-z** [comment]
Could you give me an example of how to use it please ?

**Comment by paulandrieux** [comment]
Hi, you can now refer to https://github.com/AppVentus/MangopayBundle/blob/master/README.md

**Comment by aslafy-z** [comment]
Thanks !

**Comment by paulandrieux** [comment]
Feel free to ask if this doc seems incomplete to you
